```
[Title] Univariate LSTM
[Author] Yibeck.Lee(yibeck.lee@gmail.com)
[reference]
 - https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
```

In [22]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [23]:
# split a univariate sequence into samples
from numpy import array
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [24]:
# univariate data preparation
from numpy import array
# define input sequence
import pandas as pd
df = pd.read_csv("MATERIAL_DEMAND_1.csv")
df
raw_seq = df[["TODAY_DEMAND"]][:720]
raw_seq = raw_seq.values
raw_seq
# choose a number of time steps
n_steps = 3
n_features = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[[1268]
 [1231]
 [1230]] [1200]
[[1231]
 [1230]
 [1200]] [1194]
[[1230]
 [1200]
 [1194]] [1205]
[[1200]
 [1194]
 [1205]] [1220]
[[1194]
 [1205]
 [1220]] [1218]
[[1205]
 [1220]
 [1218]] [1210]
[[1220]
 [1218]
 [1210]] [1223]
[[1218]
 [1210]
 [1223]] [1220]
[[1210]
 [1223]
 [1220]] [1190]
[[1223]
 [1220]
 [1190]] [1201]
[[1220]
 [1190]
 [1201]] [1264]
[[1190]
 [1201]
 [1264]] [1287]
[[1201]
 [1264]
 [1287]] [1295]
[[1264]
 [1287]
 [1295]] [1295]
[[1287]
 [1295]
 [1295]] [1298]
[[1295]
 [1295]
 [1298]] [1300]
[[1295]
 [1298]
 [1300]] [1302]
[[1298]
 [1300]
 [1302]] [1319]
[[1300]
 [1302]
 [1319]] [1349]
[[1302]
 [1319]
 [1349]] [1317]
[[1319]
 [1349]
 [1317]] [1305]
[[1349]
 [1317]
 [1305]] [1286]
[[1317]
 [1305]
 [1286]] [1273]
[[1305]
 [1286]
 [1273]] [1279]
[[1286]
 [1273]
 [1279]] [1266]
[[1273]
 [1279]
 [1266]] [1266]
[[1279]
 [1266]
 [1266]] [1328]
[[1266]
 [1266]
 [1328]] [1345]
[[1266]
 [1328]
 [1345]] [1339]
[[1328]
 [1345]
 [1339]] [1343]
[[1345]
 [1339]
 [1343]] [1352]
[[1339]


In [25]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [26]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], n_features))
for i in range(len(X)):
	print(X[i], y[i])

[[1268]
 [1231]
 [1230]] [1200]
[[1231]
 [1230]
 [1200]] [1194]
[[1230]
 [1200]
 [1194]] [1205]
[[1200]
 [1194]
 [1205]] [1220]
[[1194]
 [1205]
 [1220]] [1218]
[[1205]
 [1220]
 [1218]] [1210]
[[1220]
 [1218]
 [1210]] [1223]
[[1218]
 [1210]
 [1223]] [1220]
[[1210]
 [1223]
 [1220]] [1190]
[[1223]
 [1220]
 [1190]] [1201]
[[1220]
 [1190]
 [1201]] [1264]
[[1190]
 [1201]
 [1264]] [1287]
[[1201]
 [1264]
 [1287]] [1295]
[[1264]
 [1287]
 [1295]] [1295]
[[1287]
 [1295]
 [1295]] [1298]
[[1295]
 [1295]
 [1298]] [1300]
[[1295]
 [1298]
 [1300]] [1302]
[[1298]
 [1300]
 [1302]] [1319]
[[1300]
 [1302]
 [1319]] [1349]
[[1302]
 [1319]
 [1349]] [1317]
[[1319]
 [1349]
 [1317]] [1305]
[[1349]
 [1317]
 [1305]] [1286]
[[1317]
 [1305]
 [1286]] [1273]
[[1305]
 [1286]
 [1273]] [1279]
[[1286]
 [1273]
 [1279]] [1266]
[[1273]
 [1279]
 [1266]] [1266]
[[1279]
 [1266]
 [1266]] [1328]
[[1266]
 [1266]
 [1328]] [1345]
[[1266]
 [1328]
 [1345]] [1339]
[[1328]
 [1345]
 [1339]] [1343]
[[1345]
 [1339]
 [1343]] [1352]
[[1339]


In [28]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [29]:
# demonstrate prediction
x_input = array([2695, 2620, 2654])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=1)

1/1 [==============================] - 0s 438ms/step


In [30]:
yhat

array([[2657.8518]], dtype=float32)

In [31]:
raw_seq = df[["TODAY_DEMAND"]][720:]
x_input = array(raw_seq)
x_input


array([[2738],
       [2649],
       [2692],
       [2715],
       [2702],
       [2695],
       [2620],
       [2654],
       [2702],
       [2754],
       [2861],
       [2853],
       [2819],
       [2819],
       [2805]], dtype=int64)

In [32]:
X_test, y_test = split_sequence(x_input, n_steps)
for i in range(len(X_test)):
	print(X_test[i], y_test[i])

[[2738]
 [2649]
 [2692]] [2715]
[[2649]
 [2692]
 [2715]] [2702]
[[2692]
 [2715]
 [2702]] [2695]
[[2715]
 [2702]
 [2695]] [2620]
[[2702]
 [2695]
 [2620]] [2654]
[[2695]
 [2620]
 [2654]] [2702]
[[2620]
 [2654]
 [2702]] [2754]
[[2654]
 [2702]
 [2754]] [2861]
[[2702]
 [2754]
 [2861]] [2853]
[[2754]
 [2861]
 [2853]] [2819]
[[2861]
 [2853]
 [2819]] [2819]
[[2853]
 [2819]
 [2819]] [2805]


In [33]:
x_input = X_test[0].flatten()
x_input

array([2738, 2649, 2692], dtype=int64)

In [34]:
x_input = x_input.reshape((1, n_steps, n_features))
print(x_input)
yhat = model.predict(x_input, verbose=1)

[[[2738]
  [2649]
  [2692]]]
1/1 [==============================] - 0s 9ms/step


In [35]:
yhat

array([[2695.1133]], dtype=float32)

In [45]:
y_pred = []
for i in range(len(X_test)):
    x_input = X_test[i].flatten()
    x_input = x_input.reshape((1, n_steps, n_features))
#     print(x_input)
    yhat = model.predict(x_input, verbose=1)
    print(x_input, yhat)
    y_pred.append(yhat[0][0])
y_pred

1/1 [==============================] - 0s 7ms/step
[[[2738]
  [2649]
  [2692]]] [[2695.1133]]
1/1 [==============================] - 0s 4ms/step
[[[2649]
  [2692]
  [2715]]] [[2688.425]]
1/1 [==============================] - 0s 45ms/step
[[[2692]
  [2715]
  [2702]]] [[2702.2395]]
1/1 [==============================] - 0s 5ms/step
[[[2715]
  [2702]
  [2695]]] [[2703.0117]]
1/1 [==============================] - 0s 4ms/step
[[[2702]
  [2695]
  [2620]]] [[2665.0283]]
1/1 [==============================] - 0s 5ms/step
[[[2695]
  [2620]
  [2654]]] [[2657.8518]]
1/1 [==============================] - 0s 6ms/step
[[[2620]
  [2654]
  [2702]]] [[2663.9248]]
1/1 [==============================] - 0s 8ms/step
[[[2654]
  [2702]
  [2754]]] [[2709.2866]]
1/1 [==============================] - 0s 6ms/step
[[[2702]
  [2754]
  [2861]]] [[2783.597]]
1/1 [==============================] - 0s 4ms/step
[[[2754]
  [2861]
  [2853]]] [[2824.2554]]
1/1 [==============================] - 0s 3ms/step
[[[2861]
 

[2695.1133,
 2688.425,
 2702.2395,
 2703.0117,
 2665.0283,
 2657.8518,
 2663.9248,
 2709.2866,
 2783.597,
 2824.2554,
 2840.9158,
 2829.5605]