```
[Title] Univariate Stacked LSTM
[Author] Jason Brownlee
[Etidor] Yibeck.Lee(yibeck.lee@gmail.com)
[reference]
 - https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
 ```

In [1]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

Using TensorFlow backend.


In [2]:
# split a univariate sequence into samples
from numpy import array
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [3]:
# univariate data preparation


# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
n_features = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [4]:
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [5]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [6]:
# fit model
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
6/6 [==============================] - 4s 592ms/step - loss: 4377.0132
Epoch 2/200
6/6 [==============================] - 0s 2ms/step - loss: 4308.6216
Epoch 3/200
6/6 [==============================] - 0s 2ms/step - loss: 4240.6914
Epoch 4/200
6/6 [==============================] - 0s 3ms/step - loss: 4174.9409
Epoch 5/200
6/6 [==============================] - 0s 6ms/step - loss: 4109.4741
Epoch 6/200
6/6 [==============================] - 0s 3ms/step - loss: 4043.9778
Epoch 7/200
6/6 [==============================] - 0s 2ms/step - loss: 3977.6448
Epoch 8/200
6/6 [==============================] - 0s 2ms/step - loss: 3910.9324
Epoch 9/200
6/6 [==============================] - 0s 2ms/step - loss: 3842.8083
Epoch 10/200
6/6 [==============================] - 0s 3ms/step - loss: 3773.0273
Epoch 11/200
6/6 [==============================] - 0s 2ms/step - loss: 3700.7656
Epoch 12/200
6/6 [==============================] - 0s 1ms/step - loss: 3625.0059
Epoch 13/200
6/6 [=====

In [7]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=1)

1/1 [==============================] - 1s 559ms/step


In [8]:
yhat

array([[102.90307]], dtype=float32)