```
[Title] Logistic Regression for Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Logistic Regression for Classification for Prediction
```

In [6]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("../data_source/iris.csv")
data = df.values
# print(data)
# print(iris_data)
FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [7]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [8]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [9]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [10]:
# Split the data for training and testing


# Build the model

model = Sequential() 
model.add(Dense(3, input_dim=4, activation='softmax'))


# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 1s - loss: 4.2346 - acc: 0.3333
Epoch 2/200
 - 0s - loss: 3.9365 - acc: 0.3333
Epoch 3/200
 - 0s - loss: 3.6621 - acc: 0.3333
Epoch 4/200
 - 0s - loss: 3.3752 - acc: 0.3333
Epoch 5/200
 - 0s - loss: 3.1244 - acc: 0.3333
Epoch 6/200
 - 0s - loss: 2.8692 - acc: 0.3333
Epoch 7/200
 - 0s - loss: 2.6359 - acc: 0.3333
Epoch 8/200
 - 0s - loss: 2.4366 - acc: 0.3333
Epoch 9/200
 - 0s - loss: 2.2536 - acc: 0.3333
Epoch 10/200
 - 0s - loss: 2.1010 - acc: 0.3333
Epoch 11/200
 - 0s - loss: 1.9493 - acc: 0.3333
Epoch 12/200
 - 0s - loss: 1.8272 - acc: 0.3333
Epoch 13/200
 - 0s - loss: 1.7194 - acc: 0.3467
Epoch 14/200
 - 0s - lo

In [16]:
model.predict(test_x)

array([[1.01516780e-03, 5.24825871e-01, 4.74158973e-01],
       [9.34200525e-01, 6.25328273e-02, 3.26662790e-03],
       [7.54383160e-04, 2.25533351e-01, 7.73712277e-01],
       [1.04020047e-03, 3.61163884e-01, 6.37795925e-01],
       [9.75028038e-01, 2.36027446e-02, 1.36916002e-03],
       [9.77138281e-01, 2.22925581e-02, 5.69084950e-04],
       [6.02939678e-03, 4.21570510e-01, 5.72400093e-01],
       [4.21274826e-02, 6.56650841e-01, 3.01221699e-01],
       [2.77146301e-03, 6.36378467e-01, 3.60850066e-01],
       [1.57570408e-03, 2.38898039e-01, 7.59526312e-01],
       [2.02260632e-03, 4.77830321e-01, 5.20147026e-01],
       [9.56788957e-01, 4.06990945e-02, 2.51191296e-03],
       [9.53218818e-01, 4.39035036e-02, 2.87767267e-03],
       [2.33634561e-02, 5.49028993e-01, 4.27607536e-01],
       [3.23919021e-02, 5.50182045e-01, 4.17426109e-01],
       [3.88878882e-02, 6.27356470e-01, 3.33755612e-01],
       [3.50758852e-03, 4.86580163e-01, 5.09912312e-01],
       [2.28889845e-03, 5.61363

In [11]:
predicted = model.predict_classes(test_x)
print(predicted)

[2 2 1 1 1 2 1 1 1 2 2 2 0 1 0 0 0 2 1 0 0 0 2 1 2 2 1 2 1 0 2 2 1 2 1 1 1
 0 1 0 0 0 0 0 2 0 0 0 2 1 2 2 2 0 0 2 1 0 2 2 0 2 2 2 1 1 0 2 1 0 2 2 0 0
 1]


In [12]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[0. 0. 1.] 2 2
[0. 1. 0.] 1 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0


In [13]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[25,  0,  0],
       [ 0, 22,  2],
       [ 0,  0, 26]], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.9733333333333334

In [15]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9722222222222222

In [16]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9761904761904763

In [17]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.9731615673644659