```
[Title] SLP Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Single-Layer Perceptron Classification for Prediction
```

In [15]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("../data_source/iris.csv")
data = df.values
# print(data)
# print(iris_data)
FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [16]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [17]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [18]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [19]:
# Split the data for training and testing


# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 1s - loss: 1.6812 - acc: 0.3200
Epoch 2/200
 - 0s - loss: 1.5569 - acc: 0.3200
Epoch 3/200
 - 0s - loss: 1.4318 - acc: 0.3200
Epoch 4/200
 - 0s - loss: 1.3476 - acc: 0.3200
Epoch 5/200
 - 0s - loss: 1.2596 - acc: 0.3200
Epoch 6/200
 - 0s - loss: 1.1867 - acc: 0.3200
Epoch 7/200
 - 0s - loss: 1.1090 - acc: 0.3200
Epoch 8/200
 - 0s - loss: 1.0403 - acc: 0.3200
Epoch 9/200
 - 0s - loss: 0.9769 - acc: 0.3200
Epoch 10/200
 - 0s - loss: 0.9227 - acc: 0.3200
Epoch 11/200
 - 0s - loss: 0.8709 -

Epoch 158/200
 - 0s - loss: 0.1856 - acc: 0.9733
Epoch 159/200
 - 0s - loss: 0.1837 - acc: 0.9733
Epoch 160/200
 - 0s - loss: 0.1843 - acc: 0.9600
Epoch 161/200
 - 0s - loss: 0.1811 - acc: 0.9600
Epoch 162/200
 - 0s - loss: 0.1795 - acc: 0.9733
Epoch 163/200
 - 0s - loss: 0.1791 - acc: 0.9733
Epoch 164/200
 - 0s - loss: 0.1790 - acc: 0.9600
Epoch 165/200
 - 0s - loss: 0.1761 - acc: 0.9733
Epoch 166/200
 - 0s - loss: 0.1756 - acc: 0.9733
Epoch 167/200
 - 0s - loss: 0.1759 - acc: 0.9733
Epoch 168/200
 - 0s - loss: 0.1745 - acc: 0.9733
Epoch 169/200
 - 0s - loss: 0.1760 - acc: 0.9733
Epoch 170/200
 - 0s - loss: 0.1723 - acc: 0.9600
Epoch 171/200
 - 0s - loss: 0.1714 - acc: 0.9600
Epoch 172/200
 - 0s - loss: 0.1707 - acc: 0.9733
Epoch 173/200
 - 0s - loss: 0.1708 - acc: 0.9733
Epoch 174/200
 - 0s - loss: 0.1688 - acc: 0.9733
Epoch 175/200
 - 0s - loss: 0.1674 - acc: 0.9733
Epoch 176/200
 - 0s - loss: 0.1662 - acc: 0.9733
Epoch 177/200
 - 0s - loss: 0.1650 - acc: 0.9733
Epoch 178/200
 - 0s 

In [20]:
model.predict(test_x)

array([[9.90479171e-01, 9.52041335e-03, 3.51411387e-07],
       [2.96206698e-02, 9.14201438e-01, 5.61778769e-02],
       [1.07790011e-05, 1.32374451e-01, 8.67614746e-01],
       [1.89068317e-02, 8.50471020e-01, 1.30622149e-01],
       [1.66108919e-04, 4.28664476e-01, 5.71169436e-01],
       [3.33981472e-03, 8.44494224e-01, 1.52165994e-01],
       [2.13757157e-02, 9.14300680e-01, 6.43235669e-02],
       [3.62976461e-05, 2.95465261e-01, 7.04498410e-01],
       [9.91676092e-01, 8.32362473e-03, 2.47947355e-07],
       [9.91644084e-01, 8.35570600e-03, 2.53848583e-07],
       [9.90075529e-01, 9.92411282e-03, 3.85524885e-07],
       [2.30279774e-03, 8.20866764e-01, 1.76830441e-01],
       [2.06713267e-02, 9.28609729e-01, 5.07189631e-02],
       [9.25997256e-07, 7.40131289e-02, 9.25985992e-01],
       [9.73795772e-01, 2.62023844e-02, 1.89669720e-06],
       [2.12294422e-03, 8.71622384e-01, 1.26254678e-01],
       [7.23418370e-02, 8.95803809e-01, 3.18543464e-02],
       [1.12064788e-02, 8.98338

In [21]:
predicted = model.predict_classes(test_x)
print(predicted)

[0 1 2 1 2 1 1 2 0 0 0 1 1 2 0 1 1 1 0 0 2 0 0 2 1 1 0 1 2 2 1 1 0 2 2 1 1
 0 2 2 1 0 1 2 1 0 2 0 0 1 1 0 0 1 2 1 2 2 2 1 0 1 2 2 1 0 1 2 0 0 2 1 2 2
 1]


In [22]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2


In [23]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[22,  0,  0],
       [ 0, 27,  0],
       [ 0,  2, 24]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.9733333333333334

In [25]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9743589743589745

In [26]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9770114942528735

In [27]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.9747619047619048