```
[Title] MLP Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Multi-Layer Perceptron Classification for Prediction
```

In [2]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("iris.csv")
data = df.values

FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [3]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [4]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [5]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [17]:
# Split the data for training and testing


# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(20, activation='relu', name='fc2'))
model.add(Dense(20, activation='relu', name='fc3'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 20)                220       
_________________________________________________________________
fc3 (Dense)                  (None, 20)                420       
_________________________________________________________________
output (Dense)               (None, 3)                 63        
Total params: 753
Trainable params: 753
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 1s - loss: 1.0039 - acc: 0.8400
Epoch 2/200
 - 0s - loss: 0.9055 - acc: 0.9200
Epoch 3/200
 - 0s - loss: 0.8329 - acc: 0.9333
Epoch 4/200
 - 0s - loss: 0.7642 - acc: 0.9333
Epoch 5/200
 - 0s - loss: 0.6872 - acc: 0.9200
Epoch

 - 0s - loss: 0.1101 - acc: 0.9467
Epoch 153/200
 - 0s - loss: 0.0752 - acc: 0.9867
Epoch 154/200
 - 0s - loss: 0.0844 - acc: 0.9733
Epoch 155/200
 - 0s - loss: 0.0843 - acc: 0.9733
Epoch 156/200
 - 0s - loss: 0.0811 - acc: 0.9867
Epoch 157/200
 - 0s - loss: 0.0854 - acc: 0.9733
Epoch 158/200
 - 0s - loss: 0.0783 - acc: 0.9733
Epoch 159/200
 - 0s - loss: 0.0865 - acc: 0.9733
Epoch 160/200
 - 0s - loss: 0.0796 - acc: 0.9733
Epoch 161/200
 - 0s - loss: 0.0796 - acc: 0.9733
Epoch 162/200
 - 0s - loss: 0.0852 - acc: 0.9733
Epoch 163/200
 - 0s - loss: 0.0874 - acc: 0.9467
Epoch 164/200
 - 0s - loss: 0.0944 - acc: 0.9733
Epoch 165/200
 - 0s - loss: 0.0778 - acc: 0.9600
Epoch 166/200
 - 0s - loss: 0.0839 - acc: 0.9600
Epoch 167/200
 - 0s - loss: 0.0918 - acc: 0.9733
Epoch 168/200
 - 0s - loss: 0.0897 - acc: 0.9467
Epoch 169/200
 - 0s - loss: 0.0786 - acc: 0.9733
Epoch 170/200
 - 0s - loss: 0.0858 - acc: 0.9733
Epoch 171/200
 - 0s - loss: 0.0740 - acc: 0.9867
Epoch 172/200
 - 0s - loss: 0.0816

In [19]:
model.predict(test_x)

array([[5.04587893e-04, 7.04924226e-01, 2.94571221e-01],
       [9.99731481e-01, 2.58278684e-04, 1.02115346e-05],
       [4.05017374e-04, 9.73143756e-01, 2.64512300e-02],
       [4.68646618e-07, 6.74636220e-04, 9.99324918e-01],
       [1.38854317e-04, 9.99414206e-01, 4.47046419e-04],
       [5.85722912e-04, 9.96208191e-01, 3.20604164e-03],
       [2.64874689e-04, 9.83723998e-01, 1.60111021e-02],
       [5.80990445e-06, 2.92730937e-03, 9.97066915e-01],
       [5.31629994e-05, 1.43560886e-01, 8.56385946e-01],
       [1.47021046e-05, 4.08742689e-02, 9.59111094e-01],
       [9.99886513e-01, 1.09639084e-04, 3.77933338e-06],
       [1.39955373e-04, 1.94448233e-01, 8.05411816e-01],
       [9.99904990e-01, 9.01051826e-05, 4.83607482e-06],
       [1.14887700e-06, 3.04423459e-03, 9.96954560e-01],
       [4.30405344e-04, 9.94013488e-01, 5.55614475e-03],
       [9.99831319e-01, 1.56301423e-04, 1.24307944e-05],
       [2.34345411e-04, 9.98487353e-01, 1.27822638e-03],
       [9.99549329e-01, 4.41425

In [20]:
predicted = model.predict_classes(test_x)
print(predicted)

[1 0 1 2 1 1 1 2 2 2 0 2 0 2 1 0 1 0 2 0 2 2 1 1 1 2 0 0 0 0 0 2 2 0 0 2 0
 0 1 0 0 2 2 2 1 1 2 2 0 2 2 2 0 1 0 0 1 2 0 0 0 1 1 2 0 1 2 0 0 1 0 2 1 1
 1]


In [21]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0


In [22]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[28,  0,  0],
       [ 0, 22,  1],
       [ 0,  0, 24]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.9866666666666667

In [24]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9855072463768115

In [25]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9866666666666667

In [26]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.9857898715041573